# Generated by Django 3.1.5 on 2021-06-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='add name', max_length=100)),
                ('phone', models.IntegerField(default='add number')),
                ('email', models.EmailField(default='abc@edf.com', max_length=254)),
                ('complaint', models.CharField(default='add address', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='add name', max_length=100)),
                ('phone', models.IntegerField(default='add number')),
                ('email', models.EmailField(default='abc@edf.com', max_length=254)),
                ('video', models.FileField(null=True, upload_to='videos/')),
            ],
        ),
    ]
