# Generated by Django 3.1.5 on 2021-06-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_applicant_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
